export type Inquiry = {
  id: number;
  contact: string;
  venue: string;
  city: string;
  email: string;
  eventDate: string;
  deadline: string;
  type: string;
  guests: number;
  status: 'PENDING' | 'CONFIRMED' | 'CANCELLED';
}

export const inquiries: Inquiry[] = [
  {
    id: 1,
    contact: "Gregory Travis",
    venue: "Montoya and Sons Hall",
    city: "Russellmouth",
    email: "jharding@gmail.com",
    eventDate: "04-02-2026",
    deadline: "10 days ago",
    type: "Birthday",
    guests: 290,
    status: "CANCELLED",
  },
  {
    id: 2,
    contact: "John Grimes",
    venue: "Williams Group Hall",
    city: "North David",
    email: "hhopkins@yahoo.com",
    eventDate: "11-01-2026",
    deadline: "10 days ago",
    type: "Seminar",
    guests: 557,
    status: "PENDING",
  },
  {
    id: 3,
    contact: "Luke Hill",
    venue: "Bradley-Klein Hall",
    city: "Thomasmouth",
    email: "latoyastevens@dean-ruiz.com",
    eventDate: "04-02-2026",
    deadline: "4 days ago",
    type: "Workshop",
    guests: 560,
    status: "PENDING",
  },
  {
    id: 4,
    contact: "Haley Hernandez",
    venue: "Garcia Ltd Hall",
    city: "Rachelborough",
    email: "qjones@yahoo.com",
    eventDate: "10-12-2025",
    deadline: "11 days ago",
    type: "Workshop",
    guests: 331,
    status: "CONFIRMED",
  },
  {
    id: 5,
    contact: "Krystal Scott",
    venue: "Shepard PLC Hall",
    city: "North Juan",
    email: "christopher30@robinson.net",
    eventDate: "28-12-2025",
    deadline: "9 days ago",
    type: "Conference",
    guests: 301,
    status: "PENDING",
  },
  {
    id: 6,
    contact: "Wesley Nicholson",
    venue: "Cisneros-Jackson Hall",
    city: "Allenport",
    email: "robert07@yang.com",
    eventDate: "23-10-2025",
    deadline: "8 days ago",
    type: "Workshop",
    guests: 295,
    status: "CONFIRMED",
  },
  {
    id: 7,
    contact: "James Shannon",
    venue: "Duran Inc Hall",
    city: "Lake Paulburgh",
    email: "corey62@prince.net",
    eventDate: "24-12-2025",
    deadline: "6 days ago",
    type: "Seminar",
    guests: 160,
    status: "CONFIRMED",
  },
  {
    id: 8,
    contact: "Bryce Roberson",
    venue: "Carroll-Todd Hall",
    city: "Mitchellstad",
    email: "teresasmith@gmail.com",
    eventDate: "03-02-2026",
    deadline: "13 days ago",
    type: "Festival",
    guests: 679,
    status: "CONFIRMED",
  },
  {
    id: 9,
    contact: "James Johnson",
    venue: "Gaines Inc Hall",
    city: "Josephland",
    email: "jeffreygarza@yahoo.com",
    eventDate: "22-02-2026",
    deadline: "13 days ago",
    type: "Corporate Event",
    guests: 148,
    status: "CANCELLED",
  },
  {
    id: 10,
    contact: "Janice Ortega",
    venue: "Villa Inc Hall",
    city: "Brandyview",
    email: "richardschristopher@yahoo.com",
    eventDate: "19-10-2025",
    deadline: "4 days ago",
    type: "Party",
    guests: 633,
    status: "PENDING",
  },
  {
    id: 11,
    contact: "Stuart Rangel",
    venue: "Mayer PLC Hall",
    city: "Davidtown",
    email: "ifields@hotmail.com",
    eventDate: "25-02-2026",
    deadline: "8 days ago",
    type: "Engagement",
    guests: 813,
    status: "CONFIRMED",
  },
  {
    id: 12,
    contact: "Christopher Chapman",
    venue: "Davis-Cole Hall",
    city: "Lake Conniechester",
    email: "belinda16@hotmail.com",
    eventDate: "30-09-2025",
    deadline: "2 days ago",
    type: "Workshop",
    guests: 870,
    status: "CONFIRMED",
  },
  {
    id: 13,
    contact: "Jessica Hebert",
    venue: "Robertson, Thompson and Tucker Hall",
    city: "West Russell",
    email: "colemandeborah@hotmail.com",
    eventDate: "04-12-2025",
    deadline: "10 days ago",
    type: "Trade Show",
    guests: 853,
    status: "PENDING",
  },
  {
    id: 14,
    contact: "Traci Casey",
    venue: "Christian PLC Hall",
    city: "Zacharyside",
    email: "katherine90@yahoo.com",
    eventDate: "14-10-2025",
    deadline: "4 days ago",
    type: "Concert",
    guests: 750,
    status: "CANCELLED",
  },
  {
    id: 15,
    contact: "John Daniels",
    venue: "Rodriguez-Choi Hall",
    city: "Lake Rachelmouth",
    email: "nicole51@peterson.com",
    eventDate: "18-01-2026",
    deadline: "8 days ago",
    type: "New Year Gala",
    guests: 137,
    status: "CANCELLED",
  },
  {
    id: 16,
    contact: "Nathaniel Holmes",
    venue: "Anderson-Richardson Hall",
    city: "Rochahaven",
    email: "rrodriguez@johnson.info",
    eventDate: "20-01-2026",
    deadline: "11 days ago",
    type: "Party",
    guests: 489,
    status: "CONFIRMED",
  },
  {
    id: 17,
    contact: "Vicki Foster",
    venue: "Wolfe, Lindsey and Gonzalez Hall",
    city: "Taylorchester",
    email: "browncassidy@hotmail.com",
    eventDate: "16-03-2026",
    deadline: "9 days ago",
    type: "Christmas Party",
    guests: 1000,
    status: "CANCELLED",
  },
  {
    id: 18,
    contact: "Justin Guerra",
    venue: "Pugh, Murphy and Sanchez Hall",
    city: "South Alexander",
    email: "sara49@hotmail.com",
    eventDate: "06-10-2025",
    deadline: "1 days ago",
    type: "Seminar",
    guests: 832,
    status: "CONFIRMED",
  },
  {
    id: 19,
    contact: "Anthony Miller",
    venue: "Tate Ltd Hall",
    city: "New Markfurt",
    email: "xweaver@hotmail.com",
    eventDate: "06-03-2026",
    deadline: "9 days ago",
    type: "Christmas Party",
    guests: 849,
    status: "CANCELLED",
  },
  {
    id: 20,
    contact: "Judy Brown",
    venue: "Guzman-Stewart Hall",
    city: "Lake James",
    email: "brianwiley@jenkins.com",
    eventDate: "14-11-2025",
    deadline: "2 days ago",
    type: "Fundraiser",
    guests: 97,
    status: "CONFIRMED",
  },
  {
    id: 21,
    contact: "Christopher Oconnor",
    venue: "Vincent PLC Hall",
    city: "Jeanettefurt",
    email: "christopher45@martinez.com",
    eventDate: "13-03-2026",
    deadline: "6 days ago",
    type: "Seminar",
    guests: 989,
    status: "PENDING",
  },
  {
    id: 22,
    contact: "Lydia Mckinney",
    venue: "Hardy-Holloway Hall",
    city: "Port Michael",
    email: "justin25@gmail.com",
    eventDate: "11-11-2025",
    deadline: "7 days ago",
    type: "Party",
    guests: 766,
    status: "CANCELLED",
  },
  {
    id: 23,
    contact: "Erin Wilkerson",
    venue: "Garcia Group Hall",
    city: "West Jennifer",
    email: "martincraig@gmail.com",
    eventDate: "17-10-2025",
    deadline: "12 days ago",
    type: "Party",
    guests: 624,
    status: "PENDING",
  },
  {
    id: 24,
    contact: "Samantha Hoffman",
    venue: "Rios, Sanchez and Vargas Hall",
    city: "Jessefort",
    email: "gregory23@barber-lewis.com",
    eventDate: "05-10-2025",
    deadline: "11 days ago",
    type: "Conference",
    guests: 871,
    status: "CONFIRMED",
  },
  {
    id: 25,
    contact: "Vicki Walker",
    venue: "Stewart Inc Hall",
    city: "Ellisstad",
    email: "ufreeman@long.info",
    eventDate: "21-09-2025",
    deadline: "9 days ago",
    type: "New Year Gala",
    guests: 457,
    status: "CANCELLED",
  },
  {
    id: 26,
    contact: "Edward Wagner",
    venue: "Mclean, Lewis and Parker Hall",
    city: "Williamburgh",
    email: "antoniobeard@johnson.com",
    eventDate: "30-12-2025",
    deadline: "11 days ago",
    type: "Workshop",
    guests: 127,
    status: "CANCELLED",
  },
  {
    id: 27,
    contact: "Daniel Black",
    venue: "Smith LLC Hall",
    city: "Lake Stephanie",
    email: "kristyhenry@yahoo.com",
    eventDate: "27-10-2025",
    deadline: "4 days ago",
    type: "Christmas Party",
    guests: 650,
    status: "CANCELLED",
  },
  {
    id: 28,
    contact: "Joshua Dorsey",
    venue: "Lee LLC Hall",
    city: "Lake Chris",
    email: "robert59@yahoo.com",
    eventDate: "10-10-2025",
    deadline: "9 days ago",
    type: "Engagement",
    guests: 712,
    status: "CANCELLED",
  },
  {
    id: 29,
    contact: "Shannon Bennett",
    venue: "Cooper Ltd Hall",
    city: "Port Fernando",
    email: "lfoster@kim-williams.biz",
    eventDate: "22-09-2025",
    deadline: "1 days ago",
    type: "Engagement",
    guests: 788,
    status: "CONFIRMED",
  },
  {
    id: 30,
    contact: "Amy May",
    venue: "Wright PLC Hall",
    city: "New David",
    email: "cjennings@gmail.com",
    eventDate: "13-02-2026",
    deadline: "4 days ago",
    type: "New Year Gala",
    guests: 276,
    status: "CANCELLED",
  },
  {
    id: 31,
    contact: "Jose Grant",
    venue: "Oliver, Brown and Wise Hall",
    city: "West Jessica",
    email: "jtucker@hotmail.com",
    eventDate: "15-02-2026",
    deadline: "2 days ago",
    type: "New Year Gala",
    guests: 209,
    status: "CONFIRMED",
  },
  {
    id: 32,
    contact: "Julia Murray",
    venue: "Moore Group Hall",
    city: "New Michael",
    email: "lboyd@yahoo.com",
    eventDate: "24-01-2026",
    deadline: "11 days ago",
    type: "New Year Gala",
    guests: 687,
    status: "PENDING",
  },
  {
    id: 33,
    contact: "Kayla Brown",
    venue: "Hamilton LLC Hall",
    city: "Sheilachester",
    email: "birdsheri@smith.net",
    eventDate: "07-10-2025",
    deadline: "10 days ago",
    type: "New Year Gala",
    guests: 460,
    status: "PENDING",
  },
  {
    id: 34,
    contact: "William Miles",
    venue: "Braun, Campbell and Hunt Hall",
    city: "New Kurtberg",
    email: "jesse38@ward.com",
    eventDate: "12-01-2026",
    deadline: "3 days ago",
    type: "Seminar",
    guests: 582,
    status: "PENDING",
  },
  {
    id: 35,
    contact: "Jason Franklin",
    venue: "Soto-Andersen Hall",
    city: "Brownmouth",
    email: "caitlincain@gmail.com",
    eventDate: "15-12-2025",
    deadline: "5 days ago",
    type: "Fundraiser",
    guests: 464,
    status: "CANCELLED",
  },
  {
    id: 36,
    contact: "Amy Marshall",
    venue: "Hall, Warren and Banks Hall",
    city: "New Michael",
    email: "richard02@nelson.com",
    eventDate: "16-11-2025",
    deadline: "3 days ago",
    type: "Wedding",
    guests: 339,
    status: "PENDING",
  },
  {
    id: 37,
    contact: "Matthew Goodman",
    venue: "Wright-King Hall",
    city: "Carolineville",
    email: "jordan54@ortega.com",
    eventDate: "14-11-2025",
    deadline: "5 days ago",
    type: "Wedding",
    guests: 713,
    status: "PENDING",
  },
  {
    id: 38,
    contact: "Joshua Hall",
    venue: "Woods, Johnson and Smith Hall",
    city: "East Jill",
    email: "ogregory@thomas.com",
    eventDate: "12-03-2026",
    deadline: "2 days ago",
    type: "Conference",
    guests: 838,
    status: "CONFIRMED",
  },
  {
    id: 39,
    contact: "Johnathan Bailey",
    venue: "Arias-Weiss Hall",
    city: "Port Daveton",
    email: "hleon@yahoo.com",
    eventDate: "14-02-2026",
    deadline: "14 days ago",
    type: "Engagement",
    guests: 734,
    status: "PENDING",
  },
  {
    id: 40,
    contact: "Scott Oneill",
    venue: "Cohen LLC Hall",
    city: "North Shaun",
    email: "andrewleach@hotmail.com",
    eventDate: "18-12-2025",
    deadline: "6 days ago",
    type: "Party",
    guests: 185,
    status: "CONFIRMED",
  },
  {
    id: 41,
    contact: "Jeffrey Thompson",
    venue: "Lee-Mccann Hall",
    city: "Ryanbury",
    email: "stephenscott@yahoo.com",
    eventDate: "06-10-2025",
    deadline: "9 days ago",
    type: "Party",
    guests: 985,
    status: "CONFIRMED",
  },
  {
    id: 42,
    contact: "Jeremiah Cole",
    venue: "Martinez-Holland Hall",
    city: "Sanchezshire",
    email: "jacob77@hotmail.com",
    eventDate: "30-10-2025",
    deadline: "1 days ago",
    type: "Corporate Event",
    guests: 271,
    status: "PENDING",
  },
  {
    id: 43,
    contact: "Brenda Nicholson MD",
    venue: "Schultz PLC Hall",
    city: "Wilsonshire",
    email: "shane12@pacheco.com",
    eventDate: "08-01-2026",
    deadline: "1 days ago",
    type: "Christmas Party",
    guests: 340,
    status: "CANCELLED",
  },
  {
    id: 44,
    contact: "Travis Fleming",
    venue: "Garcia PLC Hall",
    city: "Annetteside",
    email: "mark18@gay.biz",
    eventDate: "01-01-2026",
    deadline: "12 days ago",
    type: "Trade Show",
    guests: 449,
    status: "PENDING",
  },
  {
    id: 45,
    contact: "Kelly Stone",
    venue: "Sutton, Gregory and Benson Hall",
    city: "Sanchezmouth",
    email: "marymartin@jackson.com",
    eventDate: "24-02-2026",
    deadline: "6 days ago",
    type: "Corporate Event",
    guests: 137,
    status: "PENDING",
  },
  {
    id: 46,
    contact: "Eric Mann",
    venue: "Chavez-Sanchez Hall",
    city: "Amandaton",
    email: "hendersonjulie@rosales.com",
    eventDate: "02-01-2026",
    deadline: "2 days ago",
    type: "Fundraiser",
    guests: 206,
    status: "PENDING",
  },
  {
    id: 47,
    contact: "Holly Pierce",
    venue: "Watkins-Stokes Hall",
    city: "East Steven",
    email: "diane83@gmail.com",
    eventDate: "24-01-2026",
    deadline: "10 days ago",
    type: "Wedding",
    guests: 968,
    status: "PENDING",
  },
  {
    id: 48,
    contact: "Pam Kim",
    venue: "Gray-Valdez Hall",
    city: "New Erikside",
    email: "gperez@gmail.com",
    eventDate: "16-01-2026",
    deadline: "14 days ago",
    type: "Christmas Party",
    guests: 358,
    status: "PENDING",
  },
  {
    id: 49,
    contact: "Susan Ortiz",
    venue: "Peterson, Williams and White Hall",
    city: "Smithstad",
    email: "mitchell73@haynes-berger.com",
    eventDate: "13-11-2025",
    deadline: "2 days ago",
    type: "Concert",
    guests: 324,
    status: "PENDING",
  },
  {
    id: 50,
    contact: "Cindy Hart",
    venue: "Brown Ltd Hall",
    city: "Chrisview",
    email: "vmann@hotmail.com",
    eventDate: "01-12-2025",
    deadline: "6 days ago",
    type: "Fundraiser",
    guests: 696,
    status: "PENDING",
  },
  {
    id: 51,
    contact: "Megan Lee",
    venue: "Holland Inc Hall",
    city: "Bookerport",
    email: "owensmolly@kane.com",
    eventDate: "06-01-2026",
    deadline: "10 days ago",
    type: "Party",
    guests: 384,
    status: "PENDING",
  },
  {
    id: 52,
    contact: "Jessica Torres",
    venue: "Murphy-Cummings Hall",
    city: "New Joanna",
    email: "jonesjade@hotmail.com",
    eventDate: "30-09-2025",
    deadline: "2 days ago",
    type: "Wedding",
    guests: 272,
    status: "CANCELLED",
  },
  {
    id: 53,
    contact: "Lawrence Johnson",
    venue: "Lowe Inc Hall",
    city: "New Johnville",
    email: "fshepard@miller-mcclure.info",
    eventDate: "18-12-2025",
    deadline: "2 days ago",
    type: "Corporate Event",
    guests: 506,
    status: "CANCELLED",
  },
  {
    id: 54,
    contact: "Joan Robinson",
    venue: "Morris Ltd Hall",
    city: "East Jessicachester",
    email: "jodygordon@haas-fitzgerald.com",
    eventDate: "08-01-2026",
    deadline: "6 days ago",
    type: "Engagement",
    guests: 132,
    status: "CONFIRMED",
  },
  {
    id: 55,
    contact: "Tami Mcdaniel",
    venue: "Smith Ltd Hall",
    city: "Millerbury",
    email: "mhull@yahoo.com",
    eventDate: "30-10-2025",
    deadline: "5 days ago",
    type: "Corporate Event",
    guests: 393,
    status: "CANCELLED",
  },
  {
    id: 56,
    contact: "Brian Estes",
    venue: "Mcgee, Michael and Jones Hall",
    city: "South Melody",
    email: "hillmason@vargas.info",
    eventDate: "06-03-2026",
    deadline: "3 days ago",
    type: "Trade Show",
    guests: 766,
    status: "CONFIRMED",
  },
  {
    id: 57,
    contact: "Robert Singh",
    venue: "Solis Inc Hall",
    city: "Port Anthonyfurt",
    email: "bryanrobinson@ellison.net",
    eventDate: "14-12-2025",
    deadline: "8 days ago",
    type: "Retirement",
    guests: 228,
    status: "CANCELLED",
  },
  {
    id: 58,
    contact: "Mark Jones",
    venue: "Crawford, Robinson and Parks Hall",
    city: "New Rose",
    email: "melissalandry@park.biz",
    eventDate: "16-10-2025",
    deadline: "14 days ago",
    type: "Wedding",
    guests: 197,
    status: "CANCELLED",
  },
  {
    id: 59,
    contact: "Caitlin Harris",
    venue: "Cardenas LLC Hall",
    city: "West Matthewhaven",
    email: "lisasanchez@garrett.com",
    eventDate: "12-01-2026",
    deadline: "1 days ago",
    type: "Christmas Party",
    guests: 186,
    status: "PENDING",
  },
  {
    id: 60,
    contact: "Joel Cruz",
    venue: "Rogers Inc Hall",
    city: "North Paul",
    email: "usmith@stevens-martin.net",
    eventDate: "20-12-2025",
    deadline: "3 days ago",
    type: "Corporate Event",
    guests: 451,
    status: "CANCELLED",
  },
  {
    id: 61,
    contact: "Dr. Harold Simon Jr.",
    venue: "Shaw-Sosa Hall",
    city: "South Jacob",
    email: "robertbaker@shannon-edwards.net",
    eventDate: "05-11-2025",
    deadline: "7 days ago",
    type: "Birthday",
    guests: 730,
    status: "CANCELLED",
  },
  {
    id: 62,
    contact: "Anthony Owens",
    venue: "King PLC Hall",
    city: "Mosleystad",
    email: "pkline@ramirez.net",
    eventDate: "14-10-2025",
    deadline: "10 days ago",
    type: "Wedding",
    guests: 102,
    status: "CANCELLED",
  },
  {
    id: 63,
    contact: "Sheila Peters",
    venue: "Anderson and Sons Hall",
    city: "Dianehaven",
    email: "diazangela@yahoo.com",
    eventDate: "16-01-2026",
    deadline: "12 days ago",
    type: "New Year Gala",
    guests: 920,
    status: "PENDING",
  },
  {
    id: 64,
    contact: "Theresa Shea",
    venue: "Brooks, Levy and Young Hall",
    city: "New Michaelland",
    email: "kerrluke@yahoo.com",
    eventDate: "27-01-2026",
    deadline: "12 days ago",
    type: "Concert",
    guests: 932,
    status: "PENDING",
  },
  {
    id: 65,
    contact: "Lauren Burgess",
    venue: "Manning-Mercado Hall",
    city: "Stephenfurt",
    email: "smithjeffrey@yahoo.com",
    eventDate: "03-12-2025",
    deadline: "10 days ago",
    type: "Retirement",
    guests: 316,
    status: "PENDING",
  },
  {
    id: 66,
    contact: "Raven Garcia",
    venue: "Evans, Martin and Ellis Hall",
    city: "Woodstad",
    email: "williamsmith@yahoo.com",
    eventDate: "03-03-2026",
    deadline: "14 days ago",
    type: "New Year Gala",
    guests: 903,
    status: "PENDING",
  },
  {
    id: 67,
    contact: "Timothy Tran",
    venue: "Lopez PLC Hall",
    city: "Rodriguezville",
    email: "zjohnson@yahoo.com",
    eventDate: "01-10-2025",
    deadline: "11 days ago",
    type: "Fundraiser",
    guests: 84,
    status: "PENDING",
  },
  {
    id: 68,
    contact: "Sandra Bradley",
    venue: "Valentine-Douglas Hall",
    city: "Robertstad",
    email: "elizabeth16@moreno.info",
    eventDate: "15-10-2025",
    deadline: "11 days ago",
    type: "Trade Show",
    guests: 873,
    status: "CANCELLED",
  },
  {
    id: 69,
    contact: "Samuel Jones",
    venue: "Harper-Walsh Hall",
    city: "Murrayborough",
    email: "wrighttammy@garcia-jones.com",
    eventDate: "27-01-2026",
    deadline: "5 days ago",
    type: "Trade Show",
    guests: 853,
    status: "PENDING",
  },
  {
    id: 70,
    contact: "Terri Harper",
    venue: "Vasquez, Lloyd and Estes Hall",
    city: "South Nancy",
    email: "jennifer91@yahoo.com",
    eventDate: "01-03-2026",
    deadline: "10 days ago",
    type: "Engagement",
    guests: 469,
    status: "CANCELLED",
  },
  {
    id: 71,
    contact: "Matthew Warren",
    venue: "Chung, Romero and Bennett Hall",
    city: "Lake Zacharyland",
    email: "michelle00@brown.com",
    eventDate: "01-10-2025",
    deadline: "7 days ago",
    type: "Christmas Party",
    guests: 291,
    status: "CONFIRMED",
  },
  {
    id: 72,
    contact: "Christopher Riley",
    venue: "Olsen-Mitchell Hall",
    city: "Smithmouth",
    email: "jessica17@gmail.com",
    eventDate: "22-02-2026",
    deadline: "7 days ago",
    type: "Fundraiser",
    guests: 217,
    status: "CANCELLED",
  },
  {
    id: 73,
    contact: "Kristen Montgomery",
    venue: "Snyder-Mclean Hall",
    city: "East Robert",
    email: "katie69@gmail.com",
    eventDate: "09-11-2025",
    deadline: "5 days ago",
    type: "Birthday",
    guests: 720,
    status: "PENDING",
  },
  {
    id: 74,
    contact: "Spencer Woods",
    venue: "Young, Smith and Glover Hall",
    city: "Pughburgh",
    email: "aroberts@yahoo.com",
    eventDate: "14-01-2026",
    deadline: "12 days ago",
    type: "Wedding",
    guests: 267,
    status: "CONFIRMED",
  },
  {
    id: 75,
    contact: "Jennifer Campbell",
    venue: "Smith, Lowery and Blake Hall",
    city: "Woodmouth",
    email: "cthompson@hotmail.com",
    eventDate: "18-02-2026",
    deadline: "7 days ago",
    type: "Corporate Event",
    guests: 988,
    status: "PENDING",
  },
  {
    id: 76,
    contact: "William Mcdaniel",
    venue: "Stevens and Sons Hall",
    city: "Chenshire",
    email: "jonesjohn@hotmail.com",
    eventDate: "10-10-2025",
    deadline: "1 days ago",
    type: "Retirement",
    guests: 536,
    status: "CANCELLED",
  },
  {
    id: 77,
    contact: "Jeffrey Smith",
    venue: "Oneill-Franklin Hall",
    city: "East Debbie",
    email: "michael78@roberts.com",
    eventDate: "04-12-2025",
    deadline: "6 days ago",
    type: "Seminar",
    guests: 272,
    status: "PENDING",
  },
  {
    id: 78,
    contact: "Victoria Pace",
    venue: "Simmons Inc Hall",
    city: "Jamesville",
    email: "wattslucas@hotmail.com",
    eventDate: "04-10-2025",
    deadline: "8 days ago",
    type: "Engagement",
    guests: 483,
    status: "PENDING",
  },
  {
    id: 79,
    contact: "Christina Williams",
    venue: "Johnson Inc Hall",
    city: "Port Michaelamouth",
    email: "ortiznicholas@richards.com",
    eventDate: "19-01-2026",
    deadline: "5 days ago",
    type: "Party",
    guests: 323,
    status: "CONFIRMED",
  },
  {
    id: 80,
    contact: "Cheryl Flores",
    venue: "Howell, Hernandez and Meza Hall",
    city: "Robinsontown",
    email: "taylorknapp@yahoo.com",
    eventDate: "19-02-2026",
    deadline: "8 days ago",
    type: "Engagement",
    guests: 105,
    status: "PENDING",
  },
  {
    id: 81,
    contact: "Jason Fisher",
    venue: "Johnson and Sons Hall",
    city: "Kayleeville",
    email: "michael94@brown.com",
    eventDate: "30-01-2026",
    deadline: "11 days ago",
    type: "Workshop",
    guests: 218,
    status: "CANCELLED",
  },
  {
    id: 82,
    contact: "Ian Diaz",
    venue: "Stokes and Sons Hall",
    city: "East Jenniferview",
    email: "parkerdavid@johnson.info",
    eventDate: "24-02-2026",
    deadline: "10 days ago",
    type: "Party",
    guests: 186,
    status: "PENDING",
  },
  {
    id: 83,
    contact: "Andrea Brooks",
    venue: "Miller, Ortiz and Gutierrez Hall",
    city: "West Alejandroton",
    email: "julie68@gmail.com",
    eventDate: "04-11-2025",
    deadline: "13 days ago",
    type: "Festival",
    guests: 958,
    status: "PENDING",
  },
  {
    id: 84,
    contact: "Megan Sherman MD",
    venue: "Roberts-Bell Hall",
    city: "New Katherine",
    email: "tiffany71@johnson.com",
    eventDate: "12-01-2026",
    deadline: "2 days ago",
    type: "Corporate Event",
    guests: 664,
    status: "CONFIRMED",
  },
  {
    id: 85,
    contact: "John Wheeler",
    venue: "Hunter LLC Hall",
    city: "Jacquelineton",
    email: "alanyork@gmail.com",
    eventDate: "05-02-2026",
    deadline: "9 days ago",
    type: "Trade Show",
    guests: 246,
    status: "CONFIRMED",
  },
  {
    id: 86,
    contact: "Eric Rivera",
    venue: "Booth-Shields Hall",
    city: "Martinezside",
    email: "robertwilson@hotmail.com",
    eventDate: "17-03-2026",
    deadline: "12 days ago",
    type: "Retirement",
    guests: 268,
    status: "CONFIRMED",
  },
  {
    id: 87,
    contact: "John Brooks",
    venue: "Nicholson PLC Hall",
    city: "Port Christopher",
    email: "fwelch@brock.com",
    eventDate: "26-02-2026",
    deadline: "7 days ago",
    type: "Conference",
    guests: 744,
    status: "CONFIRMED",
  },
  {
    id: 88,
    contact: "April Allen",
    venue: "Watkins-Hunt Hall",
    city: "Lake Henry",
    email: "ngeorge@sawyer.info",
    eventDate: "19-12-2025",
    deadline: "7 days ago",
    type: "Conference",
    guests: 644,
    status: "CANCELLED",
  },
  {
    id: 89,
    contact: "Morgan Zhang",
    venue: "Becker-Villegas Hall",
    city: "South Katherine",
    email: "chull@hotmail.com",
    eventDate: "27-12-2025",
    deadline: "1 days ago",
    type: "Festival",
    guests: 247,
    status: "PENDING",
  },
  {
    id: 90,
    contact: "Jessica King",
    venue: "Compton-White Hall",
    city: "Williamsland",
    email: "elizabeth33@petersen-duncan.com",
    eventDate: "01-11-2025",
    deadline: "11 days ago",
    type: "Corporate Event",
    guests: 893,
    status: "PENDING",
  },
  {
    id: 91,
    contact: "Thomas Martinez",
    venue: "Wilson Group Hall",
    city: "North Barbara",
    email: "gklein@gmail.com",
    eventDate: "16-02-2026",
    deadline: "12 days ago",
    type: "Corporate Event",
    guests: 601,
    status: "PENDING",
  },
  {
    id: 92,
    contact: "Megan Martinez",
    venue: "Hernandez-Castillo Hall",
    city: "Douglaston",
    email: "tammycook@johnson.net",
    eventDate: "10-10-2025",
    deadline: "10 days ago",
    type: "Christmas Party",
    guests: 899,
    status: "PENDING",
  },
  {
    id: 93,
    contact: "Kylie Beck",
    venue: "Chung-Moses Hall",
    city: "Robertville",
    email: "griffinhannah@dodson.net",
    eventDate: "02-10-2025",
    deadline: "7 days ago",
    type: "Retirement",
    guests: 916,
    status: "CANCELLED",
  },
  {
    id: 94,
    contact: "Andrew Bailey",
    venue: "Burgess Group Hall",
    city: "Nicholasville",
    email: "michaelsmith@gmail.com",
    eventDate: "28-09-2025",
    deadline: "10 days ago",
    type: "Fundraiser",
    guests: 715,
    status: "CANCELLED",
  },
  {
    id: 95,
    contact: "Angela Sanchez",
    venue: "Schultz Ltd Hall",
    city: "Dustinton",
    email: "jerry89@williams.info",
    eventDate: "23-02-2026",
    deadline: "3 days ago",
    type: "Seminar",
    guests: 299,
    status: "CONFIRMED",
  },
  {
    id: 96,
    contact: "Scott Klein",
    venue: "Moore Inc Hall",
    city: "Michaelshire",
    email: "nelsonmaria@ward.com",
    eventDate: "17-12-2025",
    deadline: "6 days ago",
    type: "Party",
    guests: 630,
    status: "CANCELLED",
  },
  {
    id: 97,
    contact: "Mrs. Jennifer Rhodes",
    venue: "Ellis Group Hall",
    city: "Port Jonathan",
    email: "valerietorres@skinner-nunez.com",
    eventDate: "14-03-2026",
    deadline: "4 days ago",
    type: "Birthday",
    guests: 982,
    status: "PENDING",
  },
  {
    id: 98,
    contact: "Joseph Green",
    venue: "Mayer, Beck and Banks Hall",
    city: "Whiteport",
    email: "ambernicholson@bradley.com",
    eventDate: "11-03-2026",
    deadline: "1 days ago",
    type: "Wedding",
    guests: 418,
    status: "PENDING",
  },
  {
    id: 99,
    contact: "Nicole Little",
    venue: "Roach-Patrick Hall",
    city: "Jeffreystad",
    email: "james99@knight.com",
    eventDate: "27-12-2025",
    deadline: "1 days ago",
    type: "Corporate Event",
    guests: 551,
    status: "CONFIRMED",
  },
  {
    id: 100,
    contact: "Jasmine Williams",
    venue: "Mendez Group Hall",
    city: "Travistown",
    email: "keith18@walters.com",
    eventDate: "04-10-2025",
    deadline: "14 days ago",
    type: "Corporate Event",
    guests: 887,
    status: "CONFIRMED",
  },
]